// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type BlogPostDocumentDataSlicesSlice = never;

/**
 * Content for blog post documents
 */
interface BlogPostDocumentData {
  /**
   * Title field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Blog Image field in *blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.blog_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  blog_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Title field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

/**
 * Item in *Footer → Inner pages*
 */
export interface FooterDocumentDataInnerPagesItem {
  /**
   * page title field in *Footer → Inner pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.inner_pages[].page_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;
}

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Social Title field in *Footer → Social Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].social_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  social_title: prismic.KeyTextField;

  /**
   * Social Icon field in *Footer → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].social_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  social_icon: prismic.ImageField<never>;

  /**
   * Social Url field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].social_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Title field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Website Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.website_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  website_logo: prismic.ImageField<never>;

  /**
   * Description field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Inner pages field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.inner_pages[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  inner_pages: prismic.GroupField<Simplify<FooterDocumentDataInnerPagesItem>>;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Email Address field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_address: prismic.KeyTextField;

  /**
   * Phone Number field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.phone_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_number: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Logo Image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Site Link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.site_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  site_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_title: prismic.KeyTextField;

  /**
   * CTA Link field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Meta Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.meta_title
   * - **Tab**: SEO and Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.meta_description
   * - **Tab**: SEO and Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.og_image
   * - **Tab**: SEO and Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | AboutSlice
  | ComplainceBadgesSlice
  | CtaSlice
  | FaqsSlice
  | TestimonialsSlice
  | PricingSlice
  | BenefitsSlice
  | CaseStudiesSlice
  | ProcessSlice
  | SectionContentSlice
  | ServicesSlice
  | SliderSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Menu → Menu Links*
 */
export interface MenuDocumentDataMenuLinksItem {
  /**
   * Link Title field in *Menu → Menu Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].link_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_title: prismic.KeyTextField;

  /**
   * Link Url field in *Menu → Menu Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[].link_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Title field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Menu Links field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  menu_links: prismic.GroupField<Simplify<MenuDocumentDataMenuLinksItem>> /**
   * Meta Title field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.meta_title
   * - **Tab**: SEO and MetaData
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.meta_description
   * - **Tab**: SEO and MetaData
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * OG Image field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.og_image
   * - **Tab**: SEO and MetaData
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice =
  | ComplainceBadgesSlice
  | AboutSlice
  | SectionContentSlice
  | ServicesSlice
  | CaseStudiesSlice
  | PlanDetailsSlice
  | PricingSlice
  | ContactFormSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes =
  | BlogPostDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | MenuDocument
  | PageDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * About Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_heading: prismic.KeyTextField;

  /**
   * isImageonLeft field in *About → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about.default.primary.isimageonleft
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  isimageonleft: prismic.BooleanField;

  /**
   * About Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  about_image: prismic.ImageField<never>;

  /**
   * About Content field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.about_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_content: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *About → secondAbout → Primary*
 */
export interface AboutSliceSecondAboutPrimary {
  /**
   * About Title field in *About → secondAbout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.secondAbout.primary.about_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_title: prismic.KeyTextField;

  /**
   * About Content field in *About → secondAbout → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.secondAbout.primary.about_content
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_content: prismic.KeyTextField;
}

/**
 * secondAbout variation for About Slice
 *
 * - **API ID**: `secondAbout`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSliceSecondAbout = prismic.SharedSliceVariation<
  "secondAbout",
  Simplify<AboutSliceSecondAboutPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault | AboutSliceSecondAbout;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Benefits → Default → Primary → Benefits Data*
 */
export interface BenefitsSliceDefaultPrimaryBenefitsDataItem {
  /**
   * Benefit Icon field in *Benefits → Default → Primary → Benefits Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.benefits_data[].benefit_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  benefit_icon: prismic.ImageField<never>;

  /**
   * Benefit Heading field in *Benefits → Default → Primary → Benefits Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.benefits_data[].benefit_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  benefit_heading: prismic.KeyTextField;

  /**
   * Benefit Description field in *Benefits → Default → Primary → Benefits Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.benefits_data[].benefit_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  benefit_description: prismic.KeyTextField;
}

/**
 * Primary content in *Benefits → Default → Primary*
 */
export interface BenefitsSliceDefaultPrimary {
  /**
   * Benefits Data field in *Benefits → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: benefits.default.primary.benefits_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  benefits_data: prismic.GroupField<
    Simplify<BenefitsSliceDefaultPrimaryBenefitsDataItem>
  >;
}

/**
 * Default variation for Benefits Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BenefitsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Benefits*
 */
type BenefitsSliceVariation = BenefitsSliceDefault;

/**
 * Benefits Shared Slice
 *
 * - **API ID**: `benefits`
 * - **Description**: Benefits
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BenefitsSlice = prismic.SharedSlice<
  "benefits",
  BenefitsSliceVariation
>;

/**
 * Item in *CaseStudies → Default → Primary → CaseStudy Data*
 */
export interface CaseStudiesSliceDefaultPrimaryCasestudyDataItem {
  /**
   * isCardonLeft field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].iscardonleft
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  iscardonleft: prismic.BooleanField;

  /**
   * Case Study Image field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].case_study_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  case_study_image: prismic.ImageField<never>;

  /**
   * brand logo image field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].brand_logo_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_logo_image: prismic.ImageField<never>;

  /**
   * Case Heading field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].case_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_heading: prismic.KeyTextField;

  /**
   * Case Description field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].case_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_description: prismic.KeyTextField;

  /**
   * Impact Point 1 field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].impact_point_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_point_1: prismic.KeyTextField;

  /**
   * Impact Point 2 field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].impact_point_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_point_2: prismic.KeyTextField;

  /**
   * Impact Point 3 field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].impact_point_3
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_point_3: prismic.KeyTextField;

  /**
   * Impact Point 4 field in *CaseStudies → Default → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[].impact_point_4
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_point_4: prismic.KeyTextField;
}

/**
 * Item in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
 */
export interface CaseStudiesSliceCaseStudySelfPrimaryCasestudyDataItem {
  /**
   * isCardonLeft field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].iscardonleft
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  iscardonleft: prismic.BooleanField;

  /**
   * Case Study Image field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].case_study_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  case_study_image: prismic.ImageField<never>;

  /**
   * brand logo image field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].brand_logo_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  brand_logo_image: prismic.ImageField<never>;

  /**
   * Case Heading field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].case_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_heading: prismic.KeyTextField;

  /**
   * Case Description field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].case_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  case_description: prismic.KeyTextField;

  /**
   * Solution field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].solution
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution: prismic.RichTextField;

  /**
   * Process field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].process
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  process: prismic.RichTextField;

  /**
   * Results field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].results
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  results: prismic.RichTextField;

  /**
   * Testimonial field in *CaseStudies → caseStudySelf → Primary → CaseStudy Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[].testimonial
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  testimonial: prismic.RichTextField;
}

/**
 * Primary content in *CaseStudies → Default → Primary*
 */
export interface CaseStudiesSliceDefaultPrimary {
  /**
   * CaseStudy Data field in *CaseStudies → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.default.primary.casestudy_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  casestudy_data: prismic.GroupField<
    Simplify<CaseStudiesSliceDefaultPrimaryCasestudyDataItem>
  >;
}

/**
 * Default variation for CaseStudies Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseStudiesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CaseStudies → caseStudySelf → Primary*
 */
export interface CaseStudiesSliceCaseStudySelfPrimary {
  /**
   * CaseStudy Data field in *CaseStudies → caseStudySelf → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_studies.caseStudySelf.primary.casestudy_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  casestudy_data: prismic.GroupField<
    Simplify<CaseStudiesSliceCaseStudySelfPrimaryCasestudyDataItem>
  >;
}

/**
 * caseStudySelf variation for CaseStudies Slice
 *
 * - **API ID**: `caseStudySelf`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudiesSliceCaseStudySelf = prismic.SharedSliceVariation<
  "caseStudySelf",
  Simplify<CaseStudiesSliceCaseStudySelfPrimary>,
  never
>;

/**
 * Slice variation for *CaseStudies*
 */
type CaseStudiesSliceVariation =
  | CaseStudiesSliceDefault
  | CaseStudiesSliceCaseStudySelf;

/**
 * CaseStudies Shared Slice
 *
 * - **API ID**: `case_studies`
 * - **Description**: CaseStudies
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseStudiesSlice = prismic.SharedSlice<
  "case_studies",
  CaseStudiesSliceVariation
>;

/**
 * Item in *ComplainceBadges → Default → Primary → Badges*
 */
export interface ComplainceBadgesSliceDefaultPrimaryBadgesItem {
  /**
   * Badge field in *ComplainceBadges → Default → Primary → Badges*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: complaince_badges.default.primary.badges[].badge
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  badge: prismic.ImageField<never>;
}

/**
 * Primary content in *ComplainceBadges → Default → Primary*
 */
export interface ComplainceBadgesSliceDefaultPrimary {
  /**
   * Badges field in *ComplainceBadges → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: complaince_badges.default.primary.badges[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  badges: prismic.GroupField<
    Simplify<ComplainceBadgesSliceDefaultPrimaryBadgesItem>
  >;
}

/**
 * Default variation for ComplainceBadges Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComplainceBadgesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComplainceBadgesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ComplainceBadges*
 */
type ComplainceBadgesSliceVariation = ComplainceBadgesSliceDefault;

/**
 * ComplainceBadges Shared Slice
 *
 * - **API ID**: `complaince_badges`
 * - **Description**: ComplainceBadges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComplainceBadgesSlice = prismic.SharedSlice<
  "complaince_badges",
  ComplainceBadgesSliceVariation
>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * CTA Heading field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_heading: prismic.KeyTextField;

  /**
   * CTA subheading field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_subheading: prismic.KeyTextField;

  /**
   * CTA Button field in *Cta → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_button: prismic.KeyTextField;

  /**
   * CTA Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Faqs → Default → Primary → Faq Data*
 */
export interface FaqsSliceDefaultPrimaryFaqDataItem {
  /**
   * Question field in *Faqs → Default → Primary → Faq Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faq_data[].question
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *Faqs → Default → Primary → Faq Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faq_data[].answer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  answer: prismic.KeyTextField;
}

/**
 * Primary content in *Faqs → Default → Primary*
 */
export interface FaqsSliceDefaultPrimary {
  /**
   * Faq Data field in *Faqs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faqs.default.primary.faq_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq_data: prismic.GroupField<Simplify<FaqsSliceDefaultPrimaryFaqDataItem>>;
}

/**
 * Default variation for Faqs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Faqs*
 */
type FaqsSliceVariation = FaqsSliceDefault;

/**
 * Faqs Shared Slice
 *
 * - **API ID**: `faqs`
 * - **Description**: Faqs
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqsSlice = prismic.SharedSlice<"faqs", FaqsSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading 1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading_1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading_1: prismic.KeyTextField;

  /**
   * Heading 2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading_2
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading_2: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * CTA1 Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta1_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta1_label: prismic.KeyTextField;

  /**
   * CTA1 Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta1_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta1_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA2 Label field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta2_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta2_label: prismic.KeyTextField;

  /**
   * CTA2 Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta2_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta2_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *PlanDetails → Default → Primary → Plan Details*
 */
export interface PlanDetailsSliceDefaultPrimaryPlanDetailsItem {
  /**
   * Plan Title field in *PlanDetails → Default → Primary → Plan Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plan_details.default.primary.plan_details[].plan_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  plan_title: prismic.KeyTextField;

  /**
   * Plan Details field in *PlanDetails → Default → Primary → Plan Details*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plan_details.default.primary.plan_details[].plan_details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  plan_details: prismic.RichTextField;
}

/**
 * Primary content in *PlanDetails → Default → Primary*
 */
export interface PlanDetailsSliceDefaultPrimary {
  /**
   * Features field in *PlanDetails → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: plan_details.default.primary.features
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features: prismic.RichTextField;

  /**
   * Plan Details field in *PlanDetails → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: plan_details.default.primary.plan_details[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  plan_details: prismic.GroupField<
    Simplify<PlanDetailsSliceDefaultPrimaryPlanDetailsItem>
  >;
}

/**
 * Default variation for PlanDetails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlanDetailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PlanDetailsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PlanDetails*
 */
type PlanDetailsSliceVariation = PlanDetailsSliceDefault;

/**
 * PlanDetails Shared Slice
 *
 * - **API ID**: `plan_details`
 * - **Description**: PlanDetails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PlanDetailsSlice = prismic.SharedSlice<
  "plan_details",
  PlanDetailsSliceVariation
>;

/**
 * Item in *Pricing → Default → Primary → Pricing Data*
 */
export interface PricingSliceDefaultPrimaryPricingDataItem {
  /**
   * Plan Title field in *Pricing → Default → Primary → Pricing Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[].plan_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  plan_title: prismic.KeyTextField;

  /**
   * Monthly Price field in *Pricing → Default → Primary → Pricing Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[].monthly_price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  monthly_price: prismic.KeyTextField;

  /**
   * Annual Price field in *Pricing → Default → Primary → Pricing Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[].annual_price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  annual_price: prismic.KeyTextField;

  /**
   * Plan Description field in *Pricing → Default → Primary → Pricing Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[].plan_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  plan_description: prismic.KeyTextField;

  /**
   * Setup Fee field in *Pricing → Default → Primary → Pricing Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[].setup_fee
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  setup_fee: prismic.KeyTextField;

  /**
   * Plan Details field in *Pricing → Default → Primary → Pricing Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[].plan_details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  plan_details: prismic.RichTextField;
}

/**
 * Primary content in *Pricing → Default → Primary*
 */
export interface PricingSliceDefaultPrimary {
  /**
   * Toggle Duration field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: pricing.default.primary.toggle_duration
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  toggle_duration: prismic.BooleanField;

  /**
   * Pricing Data field in *Pricing → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pricing.default.primary.pricing_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pricing_data: prismic.GroupField<
    Simplify<PricingSliceDefaultPrimaryPricingDataItem>
  >;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PricingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricingSlice = prismic.SharedSlice<
  "pricing",
  PricingSliceVariation
>;

/**
 * Item in *Process → Default → Primary → Card Data*
 */
export interface ProcessSliceDefaultPrimaryCardDataItem {
  /**
   * Order field in *Process → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.card_data[].order
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  order: prismic.KeyTextField;

  /**
   * Card Heading field in *Process → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.card_data[].card_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_heading: prismic.KeyTextField;

  /**
   * Card Description field in *Process → Default → Primary → Card Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.card_data[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_description: prismic.KeyTextField;

  /**
   * cardImg field in *Process → Default → Primary → Card Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.card_data[].cardimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cardimg: prismic.ImageField<never>;
}

/**
 * Primary content in *Process → Default → Primary*
 */
export interface ProcessSliceDefaultPrimary {
  /**
   * Card Data field in *Process → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process.default.primary.card_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  card_data: prismic.GroupField<
    Simplify<ProcessSliceDefaultPrimaryCardDataItem>
  >;
}

/**
 * Default variation for Process Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Process*
 */
type ProcessSliceVariation = ProcessSliceDefault;

/**
 * Process Shared Slice
 *
 * - **API ID**: `process`
 * - **Description**: Process
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSlice = prismic.SharedSlice<
  "process",
  ProcessSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SectionContent → Default → Primary*
 */
export interface SectionContentSliceDefaultPrimary {
  /**
   * Section Title field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Heading field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_heading: prismic.KeyTextField;

  /**
   * Section Description field in *SectionContent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_content.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;
}

/**
 * Default variation for SectionContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectionContent*
 */
type SectionContentSliceVariation = SectionContentSliceDefault;

/**
 * SectionContent Shared Slice
 *
 * - **API ID**: `section_content`
 * - **Description**: SectionContent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionContentSlice = prismic.SharedSlice<
  "section_content",
  SectionContentSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Services Data*
 */
export interface ServicesSliceDefaultPrimaryServicesDataItem {
  /**
   * isCardImgonLeft field in *Services → Default → Primary → Services Data*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: services.default.primary.services_data[].iscardimgonleft
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  iscardimgonleft: prismic.BooleanField;

  /**
   * Card Image field in *Services → Default → Primary → Services Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_data[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Service Title field in *Services → Default → Primary → Services Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_data[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service Description field in *Services → Default → Primary → Services Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_data[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_description: prismic.KeyTextField;

  /**
   * Points field in *Services → Default → Primary → Services Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_data[].points
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  points: prismic.RichTextField;
}

/**
 * Item in *Services → ServiceSelf → Primary → Services Data*
 */
export interface ServicesSliceServiceSelfPrimaryServicesDataItem {
  /**
   * isCardonLeft field in *Services → ServiceSelf → Primary → Services Data*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: services.serviceSelf.primary.services_data[].iscardonleft
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  iscardonleft: prismic.BooleanField;

  /**
   * Service Label field in *Services → ServiceSelf → Primary → Services Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.serviceSelf.primary.services_data[].service_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_label: prismic.KeyTextField;

  /**
   * Service Title field in *Services → ServiceSelf → Primary → Services Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.serviceSelf.primary.services_data[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service Description field in *Services → ServiceSelf → Primary → Services Data*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.serviceSelf.primary.services_data[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  service_description: prismic.RichTextField;

  /**
   * Service Image field in *Services → ServiceSelf → Primary → Services Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.serviceSelf.primary.services_data[].service_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  service_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Services Data field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_data: prismic.GroupField<
    Simplify<ServicesSliceDefaultPrimaryServicesDataItem>
  >;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Services → ServiceSelf → Primary*
 */
export interface ServicesSliceServiceSelfPrimary {
  /**
   * Services Data field in *Services → ServiceSelf → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.serviceSelf.primary.services_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_data: prismic.GroupField<
    Simplify<ServicesSliceServiceSelfPrimaryServicesDataItem>
  >;
}

/**
 * ServiceSelf variation for Services Slice
 *
 * - **API ID**: `serviceSelf`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceServiceSelf = prismic.SharedSliceVariation<
  "serviceSelf",
  Simplify<ServicesSliceServiceSelfPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault | ServicesSliceServiceSelf;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → LogoImages*
 */
export interface SliderSliceDefaultPrimaryLogoimagesItem {
  /**
   * LogoImg field in *Slider → Default → Primary → LogoImages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.logoimages[].logoimg
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logoimg: prismic.ImageField<never>;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Title field in *Slider → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * LogoImages field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.logoimages[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logoimages: prismic.GroupField<
    Simplify<SliderSliceDefaultPrimaryLogoimagesItem>
  >;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → Testimonial Data*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialDataItem {
  /**
   * Statement field in *Testimonials → Default → Primary → Testimonial Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_data[].statement
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  statement: prismic.KeyTextField;

  /**
   * User Image field in *Testimonials → Default → Primary → Testimonial Data*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_data[].user_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  user_image: prismic.ImageField<never>;

  /**
   * User Name field in *Testimonials → Default → Primary → Testimonial Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_data[].user_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  user_name: prismic.KeyTextField;

  /**
   * User Position field in *Testimonials → Default → Primary → Testimonial Data*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_data[].user_position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  user_position: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Testimonial Data field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_data[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonial_data: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialDataItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataInnerPagesItem,
      FooterDocumentDataSocialLinksItem,
      HeaderDocument,
      HeaderDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataMenuLinksItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceSecondAboutPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      AboutSliceSecondAbout,
      BenefitsSlice,
      BenefitsSliceDefaultPrimaryBenefitsDataItem,
      BenefitsSliceDefaultPrimary,
      BenefitsSliceVariation,
      BenefitsSliceDefault,
      CaseStudiesSlice,
      CaseStudiesSliceDefaultPrimaryCasestudyDataItem,
      CaseStudiesSliceDefaultPrimary,
      CaseStudiesSliceCaseStudySelfPrimaryCasestudyDataItem,
      CaseStudiesSliceCaseStudySelfPrimary,
      CaseStudiesSliceVariation,
      CaseStudiesSliceDefault,
      CaseStudiesSliceCaseStudySelf,
      ComplainceBadgesSlice,
      ComplainceBadgesSliceDefaultPrimaryBadgesItem,
      ComplainceBadgesSliceDefaultPrimary,
      ComplainceBadgesSliceVariation,
      ComplainceBadgesSliceDefault,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      FaqsSlice,
      FaqsSliceDefaultPrimaryFaqDataItem,
      FaqsSliceDefaultPrimary,
      FaqsSliceVariation,
      FaqsSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PlanDetailsSlice,
      PlanDetailsSliceDefaultPrimaryPlanDetailsItem,
      PlanDetailsSliceDefaultPrimary,
      PlanDetailsSliceVariation,
      PlanDetailsSliceDefault,
      PricingSlice,
      PricingSliceDefaultPrimaryPricingDataItem,
      PricingSliceDefaultPrimary,
      PricingSliceVariation,
      PricingSliceDefault,
      ProcessSlice,
      ProcessSliceDefaultPrimaryCardDataItem,
      ProcessSliceDefaultPrimary,
      ProcessSliceVariation,
      ProcessSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SectionContentSlice,
      SectionContentSliceDefaultPrimary,
      SectionContentSliceVariation,
      SectionContentSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryServicesDataItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceServiceSelfPrimaryServicesDataItem,
      ServicesSliceServiceSelfPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      ServicesSliceServiceSelf,
      SliderSlice,
      SliderSliceDefaultPrimaryLogoimagesItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialDataItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
