// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  benefits: dynamic(() => import("./Benefits")),
  case_studies: dynamic(() => import("./CaseStudies")),
  complaince_badges: dynamic(() => import("./ComplainceBadges")),
  contact_form: dynamic(() => import("./ContactForm")),
  cta: dynamic(() => import("./Cta")),
  faqs: dynamic(() => import("./Faqs")),
  hero: dynamic(() => import("./Hero")),
  plan_details: dynamic(() => import("./PlanDetails")),
  pricing: dynamic(() => import("./Pricing")),
  process: dynamic(() => import("./Process")),
  rich_text: dynamic(() => import("./RichText")),
  section_content: dynamic(() => import("./SectionContent")),
  services: dynamic(() => import("./Services")),
  slider: dynamic(() => import("./Slider")),
  testimonials: dynamic(() => import("./Testimonials")),
};
